# systemd-tmpfiles definition for Elemta

d /run/elemta 0755 elemta elemta -
d /var/lib/elemta 0755 elemta elemta -
d /var/log/elemta 0755 elemta elemta -
d /var/spool/elemta 0755 elemta elemta -
d /var/spool/elemta/active 0755 elemta elemta -
d /var/spool/elemta/deferred 0755 elemta elemta -
d /var/spool/elemta/held 0755 elemta elemta -
d /var/spool/elemta/failed 0755 elemta elemta -
d /var/spool/elemta/quarantine 0755 elemta elemta -
d /var/spool/elemta/data 0755 elemta elemta -
d /var/spool/elemta/tmp 0755 elemta elemta -
d /etc/elemta/conf.d 0755 root root -
d /etc/elemta/certs 0700 root root -
z /etc/elemta/elemta.toml 0600 root root -
